'use client';

import React from 'react';
import DashboardLayout from '@/components/DashboardLayout';
import RoleGate from '@/components/RoleGate';
import { MOCK_STUDENTS, type Student } from '@/lib/mock-data';
import {
  APPLICATION_CATEGORY_MAP,
  loadAdminApplications,
  saveAdminApplications,
  type ApplicationCategory,
  type AdminApplicationRecord,
} from '@/lib/admin/applications-store';
import { BriefcaseBusiness, Sparkles, Download, CheckCircle2 } from 'lucide-react';

type JobCategory = ApplicationCategory;
type JobFormState = {
  companyName: string;
  category: JobCategory;
  subcategory: string;
  studentId: string;
  jobTitle: string;
  jobDescription: string;
  date: string;
};

type AdminJobDraft = AdminApplicationRecord;

function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function toDateInputValue(d: Date) {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function buildTailoredResumeText(student: Student, job: AdminJobDraft) {
  const headline = student.baseResume?.headline || 'Student Candidate';
  const skills = Object.entries(student.baseResume?.technicalSkills || {})
    .map(([k, v]) => `${k}: ${(v || []).join(', ')}`)
    .join('\n');

  const experience = (student.baseResume?.experience || [])
    .slice(0, 2)
    .map((exp) => {
      const bullets = (exp.bullets || []).slice(0, 3).map((b) => `- ${b}`).join('\n');
      return `${exp.company} — ${exp.role} (${exp.period})\n${bullets}`;
    })
    .join('\n\n');

  return [
    `${student.name}`,
    `${student.email}`,
    ``,
    `${headline}`,
    ``,
    `TARGET ROLE`,
    `${job.category} > ${job.subcategory}`,
    ``,
    `${job.jobTitle} — ${job.companyName}`,
    ``,
    `ROLE CONTEXT (Admin-entered)`,
    `${job.jobDescription.trim().slice(0, 900)}${job.jobDescription.trim().length > 900 ? '…' : ''}`,
    ``,
    `KEY SKILLS`,
    skills || '—',
    ``,
    `RELEVANT EXPERIENCE (selected highlights)`,
    experience || '—',
    ``,
    `SUMMARY BULLETS`,
    ...(student.baseResume?.summaryBullets || []).slice(0, 5).map((b) => `- ${b}`),
    ``,
    `Generated by CareerOrbit Admin • ${new Date().toLocaleString()}`,
  ].join('\n');
}

export default function AdminJobsPage() {
  const categoryOptions = React.useMemo(() => Object.keys(APPLICATION_CATEGORY_MAP) as JobCategory[], []);
  const defaultCategory = categoryOptions[0];
  const defaultSubcategory = APPLICATION_CATEGORY_MAP[defaultCategory][0];

  const [jobs, setJobs] = React.useState<AdminJobDraft[]>(() => [
    {
      id: uid(),
      companyName: 'TechCorp',
      category: 'Software Engineering',
      subcategory: 'Frontend Developer',
      jobTitle: 'Software Engineer',
      jobDescription: 'Build and maintain web applications. Strong React/Node preferred. Experience with APIs, databases, and cloud deployments.',
      date: toDateInputValue(new Date()),
      studentId: MOCK_STUDENTS[0]?.studentId || 'unknown',
      studentName: MOCK_STUDENTS[0]?.name || 'Unknown Student',
      createdAt: Date.now(),
    },
  ]);
  const [selectedJobId, setSelectedJobId] = React.useState<string>(() => jobs[0]?.id || '');

  const [form, setForm] = React.useState<JobFormState>({
    companyName: '',
    category: defaultCategory,
    subcategory: defaultSubcategory,
    studentId: MOCK_STUDENTS[0]?.studentId || '',
    jobTitle: '',
    jobDescription: '',
    date: toDateInputValue(new Date()),
  });

  const subcategoryOptions = React.useMemo(
    () => APPLICATION_CATEGORY_MAP[form.category] || [],
    [form.category]
  );

  React.useEffect(() => {
    const saved = loadAdminApplications();
    if (saved.length === 0) return;
    const normalized = saved.map((item) => {
      if (item.studentId && item.studentName) return item;
      const fallback = MOCK_STUDENTS[0];
      return {
        ...item,
        studentId: fallback?.studentId || 'unknown',
        studentName: fallback?.name || 'Unknown Student',
      };
    });
    setJobs(normalized);
    setSelectedJobId(normalized[0]?.id || '');
  }, []);

  React.useEffect(() => {
    saveAdminApplications(jobs);
  }, [jobs]);

  const selectedJob = React.useMemo(() => jobs.find((j) => j.id === selectedJobId) || null, [jobs, selectedJobId]);
  const applicationsByCategory = React.useMemo(() => {
    const grouped: Record<JobCategory, AdminJobDraft[]> = {} as Record<JobCategory, AdminJobDraft[]>;
    for (const category of categoryOptions) grouped[category] = [];
    for (const item of jobs) grouped[item.category].push(item);
    for (const category of categoryOptions) {
      grouped[category].sort((a, b) => b.createdAt - a.createdAt);
    }
    return grouped;
  }, [categoryOptions, jobs]);

  const [selectedStudentId, setSelectedStudentId] = React.useState<string>(() => MOCK_STUDENTS[0]?.studentId || '');
  const selectedStudent = React.useMemo(() => MOCK_STUDENTS.find((s) => s.studentId === selectedStudentId) || null, [selectedStudentId]);

  const [draftText, setDraftText] = React.useState<string>('');
  const [generatedOk, setGeneratedOk] = React.useState(false);

  const canCreateJob =
    form.companyName.trim().length > 1 &&
    form.category.trim().length > 0 &&
    form.subcategory.trim().length > 1 &&
    form.studentId.trim().length > 0 &&
    form.jobTitle.trim().length > 2 &&
    form.jobDescription.trim().length > 10 &&
    /^\d{4}-\d{2}-\d{2}$/.test(form.date);

  const canGenerate = !!selectedJob && !!selectedStudent;

  const addJob = () => {
    if (!canCreateJob) return;
    const assignedStudent = MOCK_STUDENTS.find((s) => s.studentId === form.studentId);
    const newJob: AdminJobDraft = {
      id: uid(),
      companyName: form.companyName.trim(),
      category: form.category,
      subcategory: form.subcategory,
      jobTitle: form.jobTitle.trim(),
      jobDescription: form.jobDescription.trim(),
      date: form.date,
      studentId: form.studentId,
      studentName: assignedStudent?.name || 'Unknown Student',
      createdAt: Date.now(),
    };
    setJobs((cur) => [newJob, ...cur]);
    setSelectedJobId(newJob.id);
    setForm({
      companyName: '',
      category: defaultCategory,
      subcategory: defaultSubcategory,
      studentId: MOCK_STUDENTS[0]?.studentId || '',
      jobTitle: '',
      jobDescription: '',
      date: toDateInputValue(new Date()),
    });
  };

  const generateDraft = () => {
    if (!selectedJob || !selectedStudent) return;
    const text = buildTailoredResumeText(selectedStudent, selectedJob);
    setDraftText(text);
    setGeneratedOk(true);
    window.setTimeout(() => setGeneratedOk(false), 1200);
  };

  const downloadTxt = () => {
    if (!draftText) return;
    const blob = new Blob([draftText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CareerOrbit_${selectedStudent?.name || 'student'}_${selectedJob?.companyName || 'job'}.txt`.replace(/\s+/g, '_');
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <RoleGate expectedRole="admin">
      <DashboardLayout>
        <div className="space-y-6">
          <section className="rounded-3xl border border-slate-200 bg-white p-6 md:p-8">
            <div className="flex items-start justify-between gap-6 flex-wrap">
              <div>
                <p className="text-xs uppercase tracking-[0.2em] font-bold text-slate-500">Admin Workspace</p>
                <h1 className="mt-2 text-2xl md:text-3xl font-display font-black text-slate-900">Jobs</h1>
                <p className="mt-2 text-sm text-slate-500 max-w-2xl">
                  Create applications from job details and keep them organized by category. The layout separates application input (left) from resume generation (right).
                </p>
              </div>
            </div>
          </section>

          <section className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            {/* Left: Applications input */}
            <div className="rounded-3xl border border-slate-200 bg-white overflow-hidden">
              <div className="px-6 py-5 border-b border-slate-200 flex items-center justify-between gap-3 bg-slate-50/70">
                <div className="flex items-center gap-2">
                  <BriefcaseBusiness className="w-5 h-5 text-slate-700" />
                  <h2 className="text-lg font-bold text-slate-900">Add / Save Application</h2>
                </div>
                <span className="text-xs font-bold text-slate-500">{jobs.length} applications</span>
              </div>

              <div className="p-6 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="text-xs font-semibold text-slate-600">
                    Company Name
                    <input
                      value={form.companyName}
                      onChange={(e) => setForm((p) => ({ ...p, companyName: e.target.value }))}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                      placeholder="e.g., Amazon"
                    />
                  </label>
                  <label className="text-xs font-semibold text-slate-600">
                    Date
                    <input
                      type="date"
                      value={form.date}
                      onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                    />
                  </label>
                  <label className="text-xs font-semibold text-slate-600">
                    Category
                    <select
                      value={form.category}
                      onChange={(e) => {
                        const nextCategory = e.target.value as JobCategory;
                        const nextSubcategory = APPLICATION_CATEGORY_MAP[nextCategory][0] || '';
                        setForm((p) => ({
                          ...p,
                          category: nextCategory,
                          subcategory: nextSubcategory,
                          // Keep title in sync only when empty or matching prior subcategory.
                          jobTitle: p.jobTitle.trim().length === 0 || p.jobTitle === p.subcategory ? nextSubcategory : p.jobTitle,
                        }));
                      }}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                    >
                      {categoryOptions.map((cat) => (
                        <option key={cat} value={cat}>
                          {cat}
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="text-xs font-semibold text-slate-600">
                    Subcategory
                    <select
                      value={form.subcategory}
                      onChange={(e) => {
                        const nextSubcategory = e.target.value;
                        setForm((p) => ({
                          ...p,
                          subcategory: nextSubcategory,
                          jobTitle: p.jobTitle.trim().length === 0 || p.jobTitle === p.subcategory ? nextSubcategory : p.jobTitle,
                        }));
                      }}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                    >
                      {subcategoryOptions.map((sub) => (
                        <option key={sub} value={sub}>
                          {sub}
                        </option>
                      ))}
                    </select>
                  </label>

                  <label className="text-xs font-semibold text-slate-600">
                    Assign To Student
                    <select
                      value={form.studentId}
                      onChange={(e) => setForm((p) => ({ ...p, studentId: e.target.value }))}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                    >
                      {MOCK_STUDENTS.map((student) => (
                        <option key={student.studentId} value={student.studentId}>
                          {student.name} ({student.graduationYear})
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="text-xs font-semibold text-slate-600">
                    Job Title
                    <input
                      value={form.jobTitle}
                      onChange={(e) => setForm((p) => ({ ...p, jobTitle: e.target.value }))}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                      placeholder="e.g., Backend Engineer"
                    />
                  </label>
                </div>

                <label className="text-xs font-semibold text-slate-600">
                  Job Description
                  <textarea
                    value={form.jobDescription}
                    onChange={(e) => setForm((p) => ({ ...p, jobDescription: e.target.value }))}
                    className="mt-1 w-full min-h-[160px] rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-teal-600/25"
                    placeholder="Paste the job description here…"
                  />
                </label>

                <div className="flex items-center gap-3">
                  <button
                    onClick={addJob}
                    disabled={!canCreateJob}
                    className="rounded-xl bg-slate-900 text-white px-4 py-2.5 text-sm font-extrabold hover:bg-black disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Save Application
                  </button>
                  <p className="text-xs text-slate-500">
                    Tip: Save application first, then generate resume from the right panel.
                  </p>
                </div>

                <div className="pt-4 border-t border-slate-200">
                  <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Saved Applications (By Category)</p>
                  <div className="mt-3 space-y-3 max-h-[320px] overflow-y-auto pr-1">
                    {categoryOptions.map((category) => {
                      const items = applicationsByCategory[category];
                      return (
                        <div key={category} className="rounded-2xl border border-slate-200 bg-white">
                          <div className="px-4 py-2.5 border-b border-slate-100 flex items-center justify-between">
                            <p className="text-xs font-extrabold text-slate-700">{category}</p>
                            <span className="text-[11px] font-bold text-slate-500">{items.length}</span>
                          </div>
                          <div className="p-2 space-y-2">
                            {items.length === 0 && (
                              <p className="text-xs text-slate-400 px-2 py-1.5">No applications in this category.</p>
                            )}
                            {items.map((j) => {
                              const isSelected = j.id === selectedJobId;
                              return (
                                <button
                                  key={j.id}
                                  onClick={() => setSelectedJobId(j.id)}
                                  className={`w-full text-left rounded-xl border px-3 py-2.5 transition-colors ${
                                    isSelected ? 'border-indigo-200 bg-indigo-50/60' : 'border-slate-200 bg-white hover:bg-slate-50'
                                  }`}
                                >
                                  <div className="flex items-start justify-between gap-3">
                                    <div className="min-w-0">
                                      <p className="text-sm font-extrabold text-slate-900 truncate">{j.jobTitle}</p>
                                      <p className="text-xs font-semibold text-slate-500 truncate">{j.companyName}</p>
                                      <p className="text-[11px] font-semibold text-indigo-700 truncate mt-1">
                                        {j.subcategory}
                                      </p>
                                      <p className="text-[11px] font-semibold text-emerald-700 truncate mt-1">
                                        Assigned: {j.studentName}
                                      </p>
                                    </div>
                                    <span className="text-[11px] font-bold text-slate-500 whitespace-nowrap">{j.date}</span>
                                  </div>
                                </button>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            </div>

            {/* Right: Resume generator */}
            <div className="rounded-3xl border border-slate-200 bg-white overflow-hidden">
              <div className="px-6 py-5 border-b border-slate-200 flex items-center justify-between gap-3 bg-slate-50/70">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-slate-700" />
                  <h2 className="text-lg font-bold text-slate-900">Resume Generator</h2>
                </div>
                {generatedOk && (
                  <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 border border-emerald-100 px-3 py-1 text-xs font-extrabold text-emerald-800">
                    <CheckCircle2 className="w-4 h-4" /> Draft updated
                  </span>
                )}
              </div>

              <div className="p-6 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="text-xs font-semibold text-slate-600">
                    Application
                    <select
                      value={selectedJobId}
                      onChange={(e) => setSelectedJobId(e.target.value)}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900"
                    >
                      {jobs.map((j) => (
                        <option key={j.id} value={j.id}>
                          {j.jobTitle} — {j.companyName} ({j.category} / {j.subcategory}) • {j.studentName}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="text-xs font-semibold text-slate-600">
                    Student
                    <select
                      value={selectedStudentId}
                      onChange={(e) => setSelectedStudentId(e.target.value)}
                      className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900"
                    >
                      {MOCK_STUDENTS.map((s) => (
                        <option key={s.studentId} value={s.studentId}>
                          {s.name} ({s.graduationYear})
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                <div className="flex items-center gap-3">
                  <button
                    onClick={generateDraft}
                    disabled={!canGenerate}
                    className="rounded-xl bg-teal-700 text-white px-4 py-2.5 text-sm font-extrabold hover:bg-teal-800 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Generate Tailored Draft
                  </button>
                  <button
                    onClick={downloadTxt}
                    disabled={!draftText}
                    className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-extrabold text-slate-700 hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed inline-flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" /> Download
                  </button>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-slate-50/60 p-4">
                  <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Draft Preview</p>
                  <pre className="mt-3 text-xs text-slate-800 whitespace-pre-wrap font-mono bg-white border border-slate-200 rounded-2xl p-4 min-h-[320px]">
                    {draftText ||
                      'Select a job and a student, then click “Generate Tailored Draft”.\n\nThis prototype outputs a readable draft. When the backend tailor API is ready, this panel can show the real AI-generated summary + .docx download.'}
                  </pre>
                </div>
              </div>
            </div>
          </section>
        </div>
      </DashboardLayout>
    </RoleGate>
  );
}

